# Generated by Django 5.2.7 on 2025-10-26 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_address_zip_code'),
    ]

    operations = [
        migrations.RunSQL(
            '''
            INSERT INTO store_collection (title , created_at , updated_at) VALUES ('collection1', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
            ''',
            '''
            DELETE FROM store_collection WHERE title = 'collection1';
            ''',
        )
    ]
