# Generated by Django 5.2.7 on 2025-11-19 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_cart_id_alter_cartitem_cart'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product')},
        ),
    ]
