# Generated by Django 5.2.7 on 2025-11-22 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_collection_featured_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['user__first_name', 'user__last_name']},
        ),
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_name',
        ),
    ]
